services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: index_app
    restart: unless-stopped
    ports:
      - "8080:80"               
    volumes:
      # Sincronizamos el código para ver cambios en tiempo real durante el testeo
      - .:/var/www/html
      - ./logs/apache:/var/app/logs/apache2
    environment:
      DB_HOST: db
      DB_DATABASE: indexproyecto
      DB_USERNAME: root
      DB_PASSWORD: indexLIM_5825.
      APP_ENV: production
      APP_DEBUG: "false"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - index-net
    entrypoint: >
      bash -c "chown -R www-data:www-data /var/www/html/web/img/perfil 
      && chmod -R 775 /var/www/html/web/img/perfil 
      && apache2-foreground"
  db:
    image: mysql:8.0
    container_name: index_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: indexproyecto
      MYSQL_ROOT_PASSWORD: indexLIM_5825.
      # Permito conexiones desde cualquier host para que mis compañeras se puedan conectar
      MYSQL_ROOT_HOST: '%' 
    volumes:
      - db_data:/var/lib/mysql
      # importamos la base de datos indexproyecto.sql
      - ./indexproyecto.sql:/docker-entrypoint-initdb.d/importar.sql
    ports:
      - "3306:3306" # Abierto para que se pueda usar MySQL Workbench o DBeaver
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pindexLIM_5825."]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - index-net

volumes:
  db_data:

networks:
  index-net:
    driver: bridge